server {
  listen 80;
  server_name _;

  # aumenta si subirás archivos grandes
  client_max_body_size 50M;

  # Frontend
  location / {
    proxy_pass http://web:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  # API
  location /api/ {
    proxy_pass http://api:5001/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
